version: '3.9'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=Password
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql
       
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    container_name: flask
    image: snickch/flask001:PK
    restart: always
    expose:
      - 5000
    volumes:
      - ./app:/app
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    depends_on:
      - "db"

  adminer:
    image: adminer
    ports:
      - 2000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysqldb
